apiVersion: v1
kind: Pod
metadata:
  name: consumer-pod
  labels:
    app: consumer-app
spec:
  nodeName: k8s-worker02
  containers:
    - name: consumer
      image: divergentluna/kafka_consumer:latest
      ports:
        - name: consumer
          containerPort: 9092
          protocol: TCP
      # Just spin & wait forever
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]