apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-replicaset
  labels:
    app: producer-app
spec:
  template:
    metadata:
      name: producer-pod
      labels:
        app: producer-app
    spec:
      nodeName: k8s-worker01
      containers:
        - name: producer
          image: divergentluna/kafka_producer:latest
          ports:
            - name: producer
              containerPort: 9092
              protocol: TCP
          # Just spin & wait forever
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
  replicas: 2
  selector:
    matchLabels:
      app: producer-app
