apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: producer-replicaset
  labels:
    app: producer-app
spec:
  template:
    metadata:
      name: producer-pod
      labels:
        app: producer-app
    spec:
      nodeName: kube-node1
      containers:
        - name: producer
          image: divergentluna/kafka_producer:latest
          ports:
            - name: producer
              containerPort: 9092
              protocol: TCP
  replicas: 2
  selector:
    matchLabels:
      app: producer-app
